"""Add role to user and create support_ticket, message tables

Revision ID: 0e356e913191
Revises: 4fc8243bb074
Create Date: 2025-11-30 16:02:22.577244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e356e913191'
down_revision = '4fc8243bb074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_ticket',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('subject', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('creator_id', sa.Integer(), nullable=False),
        sa.Column('assignee_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['assignee_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ticket_id', sa.Integer(), nullable=False),
        sa.Column('sender_id', sa.Integer(), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['ticket_id'], ['support_ticket.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # <-- MODIFICADO: se agrega server_default para SQLite
    op.add_column(
        'user', 
        sa.Column('role', sa.String(length=20), nullable=False, server_default='user')
    )
    # opcional: eliminar el default después de poblar
    op.alter_column('user', 'role', server_default=None)

    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.drop_column('user', 'role')
    op.drop_table('message')
    op.drop_table('support_ticket')
    # ### end Alembic commands ###
